package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with absolute id = 'ReleaseManagement_OctopusExternalSystemClient'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id = AbsoluteId("ReleaseManagement_OctopusExternalSystemClient")
    name = "Octopus External System Client"

    params {
        param("GRADLE_STAGING_PLUGIN_VERSION", "%GRADLE_RELEASE_MANAGEMENT_PLUGIN_VERSION_ARTIFACTORY%")
        param("GRADLE_RELEASE_MANAGEMENT_PLUGIN_VERSION", "%GRADLE_RELEASE_MANAGEMENT_PLUGIN_VERSION_ARTIFACTORY%")
        param("PROJECT_VERSION", "1")
        param("COMPONENT_NAME", "bitbucket-client")
        param("RELENG_SKIP", "true")
    }
}))

