package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with absolute id = 'ReleaseManagement_OctopusExternalSystemClient_ReleaseManagementBitbucketClientVcsRoot'
in the project with absolute id = 'ReleaseManagement_OctopusExternalSystemClient', and delete the patch script.
*/
create(AbsoluteId("ReleaseManagement_OctopusExternalSystemClient"), GitVcsRoot({
    id = AbsoluteId("ReleaseManagement_OctopusExternalSystemClient_ReleaseManagementBitbucketClientVcsRoot")
    name = "Octopus_ExternalSystemClient_VCS"
    url = "git@github.com:octopusden/octopus-external-systems-client.git"
    branch = "main"
    branchSpec = "+:refs/heads/*"
    checkoutSubmodules = GitVcsRoot.CheckoutSubmodules.IGNORE
    userForTags = "tcagent <tcagent@openwaygroup.com>"
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.NO_MIRRORS
    authMethod = uploadedKey {
        userName = "git"
        uploadedKey = "gh-octopusden"
        passphrase = "credentialsJSON:42cbda70-eff0-410b-9c92-6fa38ad92bdb"
    }
    param("secure:password", "")
}))

